# -*- coding: utf-8 -*-
"""
/***************************************************************************
 KeycloakAuthPlugin
                                 A QGIS plugin
 Un plugin pour tester l'authentification via Keycloak
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-02-15
        copyright            : (C) 2023 by IGN
        email                : orka.cruze@ign.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import os
from pathlib import Path


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load KeycloakAuthPlugin class from file KeycloakAuthPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .keycloak_auth_plugin import KeycloakAuthPlugin

    return KeycloakAuthPlugin(iface)
